// <auto-generated />
using System;
using FileuploadingCSV;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileuploadingCSV.Migrations
{
    [DbContext(typeof(CitiesDemoDbContext))]
    [Migration("20230421070237_MyNewCities")]
    partial class MyNewCities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FileuploadingCSV.Model.Cities", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("capital")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("citiesno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city_ascii")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iso2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iso3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lng")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("population")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("cities");
                });
#pragma warning restore 612, 618
        }
    }
}
